version: '3'
services:
  node:
    container_name: node
    build:
      context: ./node
    volumes:
      - ./node:/usr/src/app
    restart: always
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db   
    networks:
      - node-network

  db:
    image: mysql:8.0.25
    # image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./database/tbpeople.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "8070:80"
    networks:
      - node-network
    depends_on:
      - node      
      
networks:
  node-network:
    driver: bridge
