version: '3'

services:

  app:
    build:
      context: node
    container_name: app
    # entrypoint: dockerize -wait tcp://db:3306 -timeout 50s node index.js
    entrypoint: npm install express --save node index.js
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "8070:3000"
    networks:
      - node-network
    depends_on:
      - db

  nginx:
    build:
      context: nginx
    container_name: nginx
    restart: always
    networks:
      - node-network
    ports:
      - "8080:8080"
    depends_on:
      - db      

  db:
    image: mysql:8.0.25
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./database/tbpeople.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
      
networks:
  node-network:
    driver: bridge
