version: '3'
services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "8070:80"
    networks:
      - node-network
    depends_on:
      - node   

  node:
    container_name: node
    build:
      context: ./node
    volumes:
      - ./node:/usr/src/app
    restart: always
    tty: true
    depends_on:
      - db   
    networks:
      - node-network

  db:
    image: mysql:8.0.25
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    networks:
      - node-network
    volumes:
      - ./mysql:/var/lib/mysql
      - ./database/tbpeople.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      
networks:
  node-network:
    driver: bridge
