version: '3'
services:
  node:
    container_name: node
    build:
      context: ./node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm install && node index.js"
    restart: always
    tty: true
    volumes:
      - ./node:/usr/src/app
    depends_on:
      - db   
    networks:
      - node-network
    ports:
      - "3000:3000"

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./database/tbpeople.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    networks:
      - node-network
    depends_on:
      - node      
    ports:
      - "8080:80"
      
networks:
  node-network:
    driver: bridge
